---
driver:
  name: ec2
  aws_ssh_key_id: emea-sa-shared
  region: eu-west-1
  availability_zone: a
  instance_type: t2.micro
  security_group_ids: ['sg-50658837']
  subnet_id: subnet-4bdd1d2f
  retryable_tries: 120

provisioner:
  name: chef_solo

platforms:
  - name: rhel-7

transport:
  ssh_key: ~/.ssh/emea-sa-shared

suites:
  - name: default
    run_list:
      - recipe[sa-hardening::default]
    attributes:
